version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/scrape
permissions:
  - object: /home/ec2-user/scrape
    owner: ec2-user
    group: ec2-user    
hooks:
  AfterInstall:
    - location: scripts/install.bash
      runas: ec2-user
